/**
 * PDF Generation Utility
 * Pure JS implementation - no external libraries needed
 */

import { Patient } from '../hooks/usePatients';

export class PDFGenerator {
  /**
   * Generate PDF for shift handoff report
   */
  static async generateShiftHandoffPDF(data: {
    patients: any[];
    nurseName: string;
    shift: 'day' | 'night';
    floor: number;
    ward: string;
  }): Promise<void> {
    const { patients, nurseName, shift, floor, ward } = data;
    const timestamp = new Date().toLocaleString();
    
    // Create printable content
    const content = this.createShiftHandoffHTML(patients, nurseName, shift, floor, ward, timestamp);
    
    // Create temporary print window
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to generate PDF');
      return;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Shift Handoff Report - ${timestamp}</title>
          <style>
            ${this.getPrintStyles()}
          </style>
        </head>
        <body>
          ${content}
          <script>
            window.onload = function() {
              window.print();
              setTimeout(() => window.close(), 100);
            }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }

  /**
   * Generate PDF for patient detail report
   */
  static async generatePatientPDF(patient: Patient): Promise<void> {
    const timestamp = new Date().toLocaleString();
    
    const content = this.createPatientDetailHTML(patient, timestamp);
    
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to generate PDF');
      return;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Patient Report - ${patient.name} - ${timestamp}</title>
          <style>
            ${this.getPrintStyles()}
          </style>
        </head>
        <body>
          ${content}
          <script>
            window.onload = function() {
              window.print();
              setTimeout(() => window.close(), 100);
            }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }

  private static createShiftHandoffHTML(
    patients: any[],
    nurseName: string,
    shift: string,
    floor: number,
    ward: string,
    timestamp: string
  ): string {
    const shiftTimes = {
      day: '06:00 – 18:00',
      night: '18:00 – 06:00'
    };

    const criticalCount = patients.filter(p => p.riskLevel === 'critical').length;
    const highRiskCount = patients.filter(p => p.riskLevel === 'high').length;

    return `
      <div class="report-container">
        <div class="header">
          <h1>🏥 ICU Shift Handoff Report</h1>
          <p class="timestamp">${timestamp}</p>
        </div>

        <div class="summary-section">
          <h2>Shift Summary</h2>
          <table class="summary-table">
            <tr>
              <td><strong>Nurse:</strong></td>
              <td>${nurseName}</td>
              <td><strong>Shift:</strong></td>
              <td>${shift.charAt(0).toUpperCase() + shift.slice(1)} (${shiftTimes[shift as 'day' | 'night']})</td>
            </tr>
            <tr>
              <td><strong>Location:</strong></td>
              <td>Floor ${floor} — Ward ${ward}</td>
              <td><strong>Total Patients:</strong></td>
              <td>${patients.length}</td>
            </tr>
            <tr>
              <td><strong>Critical:</strong></td>
              <td style="color: #dc2626;">${criticalCount}</td>
              <td><strong>High Risk:</strong></td>
              <td style="color: #f59e0b;">${highRiskCount}</td>
            </tr>
          </table>
        </div>

        <div class="patients-section">
          <h2>Patient Details</h2>
          ${patients.map(patient => this.createPatientCard(patient)).join('')}
        </div>

        <div class="footer">
          <p>Generated by VitalX ICU Digital Twin System</p>
          <p>This report contains confidential patient information - Handle according to HIPAA guidelines</p>
        </div>
      </div>
    `;
  }

  private static createPatientCard(patient: any): string {
    const riskColors: Record<string, string> = {
      critical: '#dc2626',
      high: '#f59e0b',
      medium: '#eab308',
      low: '#22c55e'
    };
    const riskColor = riskColors[patient.riskLevel as string] || '#6b7280';

    const criticalVitals: string[] = [];
    if (patient.vitals.heartRate > 120 || patient.vitals.heartRate < 60) {
      criticalVitals.push(`HR: ${patient.vitals.heartRate} bpm`);
    }
    if (patient.vitals.spo2 < 92) {
      criticalVitals.push(`SpO2: ${patient.vitals.spo2}%`);
    }
    if (patient.vitals.systolicBP < 90 || patient.vitals.systolicBP > 180) {
      criticalVitals.push(`BP: ${patient.vitals.systolicBP}/${patient.vitals.diastolicBP}`);
    }

    return `
      <div class="patient-card" style="border-left: 4px solid ${riskColor};">
        <div class="patient-header">
          <h3>${patient.name}</h3>
          <span class="risk-badge" style="background-color: ${riskColor};">
            ${patient.riskLevel.toUpperCase()} RISK
          </span>
        </div>
        
        <div class="patient-info">
          <p><strong>Bed:</strong> ${patient.bed} | <strong>Age:</strong> ${patient.age} years</p>
          <p><strong>Diagnosis:</strong> ${patient.diagnosis}</p>
        </div>

        <div class="vitals-grid">
          <div class="vital-item">
            <span class="vital-label">Heart Rate</span>
            <span class="vital-value">${patient.vitals.heartRate} bpm</span>
          </div>
          <div class="vital-item">
            <span class="vital-label">Blood Pressure</span>
            <span class="vital-value">${patient.vitals.systolicBP}/${patient.vitals.diastolicBP} mmHg</span>
          </div>
          <div class="vital-item">
            <span class="vital-label">SpO2</span>
            <span class="vital-value">${patient.vitals.spo2}%</span>
          </div>
          <div class="vital-item">
            <span class="vital-label">Temp</span>
            <span class="vital-value">${patient.vitals.temperature}°C</span>
          </div>
          <div class="vital-item">
            <span class="vital-label">Resp Rate</span>
            <span class="vital-value">${patient.vitals.respiratoryRate} br/min</span>
          </div>
        </div>

        ${criticalVitals.length > 0 ? `
          <div class="critical-alerts">
            <strong>⚠️ Critical Vitals:</strong>
            <ul>
              ${criticalVitals.map(v => `<li>${v}</li>`).join('')}
            </ul>
          </div>
        ` : ''}

        ${patient.alerts && patient.alerts.length > 0 ? `
          <div class="recent-alerts">
            <strong>Recent Alerts:</strong>
            <ul>
              ${patient.alerts.slice(0, 3).map((alert: any) => `<li>${alert.message}</li>`).join('')}
            </ul>
          </div>
        ` : ''}

        ${patient.nurseNotes ? `
          <div class="nurse-notes">
            <strong>Handoff Notes:</strong>
            <p>${patient.nurseNotes}</p>
          </div>
        ` : ''}
      </div>
    `;
  }

  private static createPatientDetailHTML(patient: Patient, timestamp: string): string {
    const riskScore = patient.latest_risk_score || 0;
    const riskLevel = riskScore > 0.8 ? 'CRITICAL' : riskScore > 0.5 ? 'HIGH' : riskScore > 0.3 ? 'MEDIUM' : 'LOW';
    const riskColor = riskScore > 0.8 ? '#dc2626' : riskScore > 0.5 ? '#f59e0b' : riskScore > 0.3 ? '#eab308' : '#22c55e';

    return `
      <div class="report-container">
        <div class="header">
          <h1>📋 Patient Detail Report</h1>
          <p class="timestamp">${timestamp}</p>
        </div>

        <div class="patient-overview">
          <div class="patient-header">
            <h2>${patient.name}</h2>
            <span class="risk-badge" style="background-color: ${riskColor};">
              ${riskLevel} RISK (${(riskScore * 100).toFixed(1)}%)
            </span>
          </div>
          <p><strong>Bed:</strong> ${patient.bed_number} | <strong>Floor:</strong> ${patient.floor}</p>
          <p><strong>Patient ID:</strong> ${patient.patient_id}</p>
        </div>

        <div class="vitals-section">
          <h3>Current Vital Signs</h3>
          <table class="vitals-table">
            <tr>
              <td><strong>Heart Rate:</strong></td>
              <td>${patient.vitals.heart_rate} bpm</td>
              <td><strong>Blood Pressure:</strong></td>
              <td>${patient.vitals.systolic_bp}/${patient.vitals.diastolic_bp} mmHg</td>
            </tr>
            <tr>
              <td><strong>Respiratory Rate:</strong></td>
              <td>${patient.vitals.respiratory_rate} br/min</td>
              <td><strong>SpO2:</strong></td>
              <td>${patient.vitals.spo2}%</td>
            </tr>
            <tr>
              <td><strong>Temperature:</strong></td>
              <td>${patient.vitals.temperature.toFixed(1)}°C</td>
              <td><strong>Status:</strong></td>
              <td>${patient.state || 'Monitoring'}</td>
            </tr>
          </table>
        </div>

        ${patient.anomaly_flag ? `
          <div class="alert-box">
            <strong>⚠️ ANOMALY DETECTED</strong>
            <p>This patient has been flagged for abnormal vital sign patterns. Immediate review recommended.</p>
          </div>
        ` : ''}

        <div class="footer">
          <p>Generated by VitalX ICU Digital Twin System</p>
          <p>CONFIDENTIAL - Protected Health Information (PHI)</p>
        </div>
      </div>
    `;
  }

  private static getPrintStyles(): string {
    return `
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      body {
        font-family: Arial, Helvetica, sans-serif;
        line-height: 1.6;
        color: #333;
        padding: 20px;
        background: white;
      }

      .report-container {
        max-width: 800px;
        margin: 0 auto;
      }

      .header {
        text-align: center;
        border-bottom: 3px solid #2563eb;
        padding-bottom: 20px;
        margin-bottom: 30px;
      }

      .header h1 {
        color: #1e40af;
        font-size: 28px;
        margin-bottom: 10px;
      }

      .timestamp {
        color: #666;
        font-size: 14px;
      }

      .summary-section, .vitals-section, .patients-section {
        margin-bottom: 30px;
      }

      h2, h3 {
        color: #1e40af;
        margin-bottom: 15px;
        border-bottom: 2px solid #e5e7eb;
        padding-bottom: 8px;
      }

      .summary-table, .vitals-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
      }

      .summary-table td, .vitals-table td {
        padding: 10px;
        border: 1px solid #e5e7eb;
      }

      .summary-table tr:nth-child(even),
      .vitals-table tr:nth-child(even) {
        background-color: #f9fafb;
      }

      .patient-card {
        background: white;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
        page-break-inside: avoid;
      }

      .patient-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 15px;
      }

      .patient-header h3 {
        margin: 0;
        border: none;
        font-size: 20px;
      }

      .risk-badge {
        color: white;
        padding: 6px 12px;
        border-radius: 4px;
        font-size: 12px;
        font-weight: bold;
      }

      .patient-info {
        margin-bottom: 15px;
        color: #666;
      }

      .vitals-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 15px;
        margin-bottom: 15px;
      }

      .vital-item {
        display: flex;
        flex-direction: column;
      }

      .vital-label {
        font-size: 12px;
        color: #666;
        text-transform: uppercase;
      }

      .vital-value {
        font-size: 18px;
        font-weight: bold;
        color: #333;
      }

      .critical-alerts, .recent-alerts, .nurse-notes {
        background: #fef3c7;
        border-left: 4px solid #f59e0b;
        padding: 12px;
        margin-top: 15px;
      }

      .critical-alerts {
        background: #fee2e2;
        border-color: #dc2626;
      }

      .critical-alerts ul, .recent-alerts ul {
        margin-left: 20px;
        margin-top: 8px;
      }

      .alert-box {
        background: #fee2e2;
        border: 2px solid #dc2626;
        border-radius: 8px;
        padding: 15px;
        margin: 20px 0;
        text-align: center;
      }

      .alert-box strong {
        color: #dc2626;
        font-size: 18px;
      }

      .patient-overview {
        background: #f9fafb;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 30px;
      }

      .footer {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 2px solid #e5e7eb;
        text-align: center;
        font-size: 12px;
        color: #666;
      }

      @media print {
        body {
          padding: 0;
        }
        
        .patient-card {
          page-break-inside: avoid;
        }
      }
    `;
  }
}
